module.exports = [
  "BOOYAKASHA!",
  "Lana. Lana. Lana! LANAAA!!!",
  "WOOOO!!!",
  "DANGER ZONE!",
  "I'm Randy Magnum, local Emmy-winning cameraman and nationally ranked pro kite surfer.",
  "Do you not see me rocking this chiseled slab of hard man body? I mean come on.",
  "Because how hard is it to poach a god damn egg properly? Seriously, that's like eggs 101 Woodhouse.",
  "Woodhouse! What are you doing?",
  "Hey, wanna smell something?",
  "I swear I had something for this.",
  "Phrasing!",
  "Duh and/or hello!",
  "ARE YOU OUT OF YOUR MIND?",
  "Woah woah woah, I thought nobody else was supposed to know about this.",
  "Um, phrasing.",
  "Hey com 'on, you know I'd never let anything happen to your bacon. I love you Santa Clause. *sniff* I do.",
  "I am drunk, or I wouldn't be talking to you.",
  "Lying is like 95% of what I do.",
  "That is so classic her.",
  "That is so classic mother.",
  "Can't or won't?",
  "Doesn't it?",
  "DANGER ZONE!",
  "Well obviously!",
  "Something something danger zone. I know. I'm not even trying anymore.",
  "You know what's dangerous? You're obsession with me. Seriously, Lana, call Kenny Loggins, 'cause you're in the Danger Zone.",
  "Why, because you shoot them?",
  "Yeah, like I told you he would, you idiot.",
  "Karate: the Dane Cook of martial arts? No. ISIS agents use Krav Maga. We got an ex-Mossad guy who comes in on Thursdays.",
  "Uh, hello. Herpes.",
  "No, I think Jenga's a game."
];